/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan5;

/**
 *
 * @author MirzaUY
 */
public class frame2 extends javax.swing.JFrame {
    /**
     * Creates new form frame2
     */
       public frame2(String nama,String absen,String jurusan,String alamat,String kls) {
        initComponents();
       Nama.setText(nama);
       Absen.setText(absen);
       Jurusan.setText(jurusan);
       Alamat.setText(alamat);
       Kelas.setText(kls);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Bebas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("HASIL BIODATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(124, 26, 153, 33);

        Nama.setBackground(new java.awt.Color(204, 204, 204));
        Nama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nama.setForeground(new java.awt.Color(204, 204, 204));
        Nama.setText("NAMA");
        jPanel1.add(Nama);
        Nama.setBounds(150, 90, 41, 19);

        Kelas.setBackground(new java.awt.Color(204, 204, 204));
        Kelas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Kelas.setForeground(new java.awt.Color(204, 204, 204));
        Kelas.setText("KELAS");
        jPanel1.add(Kelas);
        Kelas.setBounds(150, 170, 80, 19);

        Jurusan.setBackground(new java.awt.Color(204, 204, 204));
        Jurusan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Jurusan.setForeground(new java.awt.Color(204, 204, 204));
        Jurusan.setText("JURUSAN");
        jPanel1.add(Jurusan);
        Jurusan.setBounds(150, 210, 66, 19);

        Absen.setBackground(new java.awt.Color(204, 204, 204));
        Absen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Absen.setForeground(new java.awt.Color(204, 204, 204));
        Absen.setText("ABSEN");
        jPanel1.add(Absen);
        Absen.setBounds(150, 130, 47, 19);

        Alamat.setBackground(new java.awt.Color(204, 204, 204));
        Alamat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Alamat.setForeground(new java.awt.Color(204, 204, 204));
        Alamat.setText("ALAMAT");
        jPanel1.add(Alamat);
        Alamat.setBounds(150, 250, 56, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Latihan5/ts.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 10, 270, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
